### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by liveresume** [codegangsta/gin#108]
Seemed simple enough but...

```
root@78a7bd737fc9:/backend# gin  --path ./src
[gin] listening on port 7070
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x470e20]

goroutine 1 [running]:
panic(0x70e500, 0xc4200120a0)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/codegangsta/gin/lib.(*builder).Build(0xc420014480, 0xc42004d6e0, 0xc42004d6d0)
	/go/src/github.com/codegangsta/gin/lib/builder.go:62 +0x340
main.build(0x8ce360, 0xc420014480, 0x8cefe0, 0xc4200144e0, 0xc420016690)
	/go/src/github.com/codegangsta/gin/main.go:180 +0x64
main.MainAction(0xc420098500)
	/go/src/github.com/codegangsta/gin/main.go:157 +0x88d
gopkg.in/urfave/cli%2ev1.HandleAction(0x6f1c20, 0x790b98, 0xc420098500, 0xc420014420, 0x0)
	/go/src/gopkg.in/urfave/cli.v1/app.go:487 +0x7c
gopkg.in/urfave/cli%2ev1.(*App).Run(0xc420092d00, 0xc42000c0e0, 0x7, 0x7, 0x0, 0x0)
	/go/src/gopkg.in/urfave/cli.v1/app.go:259 +0x74f
main.main()
	/go/src/github.com/codegangsta/gin/main.go:103 +0x96d

```

**Comment by inadarei** [comment]
I had a similar issue and after some investigation the cause ended-up being: gin unable to connect to the back-end service.

**Comment by liveresume** [comment]
Not sure what ended up resolving this, but it works.
